# `docker stack deploy -c /home/pi/projects/piarmy-scripts/swarm/piarmy-minio-stack.yml piarmy`

version: '3'

services:
  minio1:
    image: pixelchrome/minio-arm:latest
    volumes:
      - /media/usb/export:/export
    ports:
      - "9001:9000"
    networks:
      - piarmy
    deploy:
      placement:
        constraints:
          - node.labels.name == piarmy01
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    environment:
      MINIO_ACCESS_KEY: piarmyPIARMY
      MINIO_SECRET_KEY: PIARMYpiarmy

  minio2:
    image: pixelchrome/minio-arm:latest
    volumes:
      - /media/usb/export:/export
    ports:
      - "9002:9000"
    networks:
      - piarmy
    deploy:
      placement:
        constraints:
          - node.labels.name == piarmy02
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    environment:
      MINIO_ACCESS_KEY: piarmyPIARMY
      MINIO_SECRET_KEY: PIARMYpiarmy

  minio3:
    image: pixelchrome/minio-arm:latest
    volumes:
      - /media/usb/export:/export
    ports:
      - "9003:9000"
    networks:
      - piarmy
    deploy:
      placement:
        constraints:
          - node.labels.name == piarmy03
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    environment:
      MINIO_ACCESS_KEY: piarmyPIARMY
      MINIO_SECRET_KEY: PIARMYpiarmy

  minio4:
    image: pixelchrome/minio-arm:latest
    volumes:
      - /media/usb/export:/export
    ports:
      - "9004:9000"
    networks:
      - piarmy
    deploy:
      placement:
        constraints:
          - node.labels.name == piarmy04
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
    environment:
      MINIO_ACCESS_KEY: piarmyPIARMY
      MINIO_SECRET_KEY: PIARMYpiarmy

networks:  
  piarmy:
    external: true
